steps:
- label: ":pipeline: Generate dynamic pipeline"
  key: "pipeline-gen"
  plugins:
  - kubernetes:
      podSpec:
        containers:
        - image: docker.io/vespaengine/vespa-build-almalinux-8
          command: [sh, -c]
          args:
          - "'cd .buildkite && go get && (go run main.go | buildkite-agent pipeline upload)'"
